architecture:
  has_attention: true
  has_conv_layers: true
  has_gru: false
  has_lstm: true
  has_squeeze_excite: false
author: Local Dialect Speech Team
created_at: '2025-09-15T21:25:52.830012'
description: Advanced Twi speech intent recognition model trained on local dialect
  data
hidden_dim: 128
input_dim: 39
license: MIT
model_name: TwiSpeechIntentClassifier
model_type: intent_only
num_classes: 49
package_version: 1.0.0
tags:
- speech-recognition
- twi
- intent-classification
- local-dialect
- africa
version: 1.0.0
