services:
  - type: web
    name: akan-twi-speech-api
    runtime: python
    plan: starter
    buildCommand: "pip install -r deployable_twi_speech_model/requirements.txt"
    startCommand: "python start_simple_render.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ENVIRONMENT
        value: "production"
      - key: LOG_LEVEL
        value: "INFO"
      - key: RENDER_DEBUG
        value: "1"
    healthCheckPath: /health
    autoDeploy: true
