services:
  # Web service
  - type: web
    name: akan-twi-speech-api
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: MODEL_PATH
        value: data/models_improved/best_model.pt
      - key: LABEL_MAP_PATH
        value: data/processed_augmented/label_map.npy
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /health
    disk:
      name: model-data
      mountPath: /app/data
      sizeGB: 10
